### PR TITLE
Added CSP and CORS headers

### PR DESCRIPTION
**Pull request by niko391a**
Added CSP and CORS headers, for now only manually tested by using the browsers network and console tool.

Stay out hackerman:

̿̿ ̿̿ ̿̿ ̿'̿'\\з= ( ▀ ͜͞ʖ▀) =ε//’̿’̿ ̿ ̿̿ ̿̿ ̿̿

### CODE REVIEW

**Review by Nikolaj787 — APPROVED** [review]
Looks great! Nice to see that we now have implemented Cors

**Review by RasmusAChr — CHANGES_REQUESTED** [review]
Great implementation of CORS and CSP. 

However it is a bit unclear what the code on line 97 does, and it would be great to have a comment to describe the lines of code.

**Comment by DragonFlyersx** [comment]
> Great implementation of CORS and CSP.
> 
> However it is a bit unclear what the code on line 97 does, and it would be great to have a comment to describe the lines of code.

Should be changed now

**Review by RasmusAChr — APPROVED** [review]
Great comments

**Pull request merged**
