### PR TITLE
Optimized visual layout for phones

### PR DESCRIPTION
**Pull request by RasmusAChr**
<h1 align="center">Mobile Layout For Chirp!</h1>
<div align="center">
  <table>
    <tr>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </table>
</div>
<h2 align="center">Whats new?</h2>
<div align="center">
  <table>
    <tr><td>An all new navigation bar for mobile</td></tr>
    <tr><td>New register icon for more clarity</td></tr>
    <tr><td>More dense Chirp icon to match rest of the icons</td></tr>
    <tr><td>New css file for modifying mobile layout</td></tr>
  </table>
</div>
<h2 align="center">Under the hood</h2>
<ul>
<li>The mobile layout is designed so that users with a device width smaller than 481px will see the mobile layout.</li><br>
<li>When using the mobile layout, the mobile navigation bar will be displayed, which is a completely separate component from the normal navigation bar.</li><br>
<li>The visibility is controlled by the CSS property <code>display: none;</code>, which is applied based on the type of device being used.</li>
</ul>
<div align="center">
  XOsX
</div>

### CODE REVIEW

**Review by Nikolaj787 — APPROVED** [review]
Great changes to make the mobile layout more fitting!

**Review by Tipskind — APPROVED** [review]
Looks very cool. Great work on the new front-end.

**Review by niko391a — COMMENTED** [review]
Damn this is a very clean pull request man 🔥

**Review by niko391a — APPROVED** [review]
The new layout looks intuitive and user friendly. Great Work!

**Review by DragonFlyersx — APPROVED** [review]
Looks great adds way better usability on the phone great job

**Pull request merged**
