### PR TITLE
Css background - Enhancement

### PR DESCRIPTION
**Pull request by niko391a**
# New Background
ezgif-6-99e9a72ee7

Background now consists of a gradient that slowly blends into an image at the bottom. 
- Dark version images also added in folder in case of future dark and light mode switch.

༼ つ ◕_◕ ༽つ < *Fancy Stuff* >

### CODE REVIEW

**Review by Tipskind — APPROVED** [review]
Looks very nice. Would like to see some changes to the top of the background to add variety while not looking at the bottom. It would eb best to fit the side buttons in a frame, if you should implement these changes.

**Review by Nikolaj787 — APPROVED** [review]
Great visual changes. Very good very nice!

**Review by RasmusAChr — APPROVED** [review]
DAYMN MA BOY HAS BEEN COOKING!

**Review by DragonFlyersx — APPROVED** [review]
This is honestly really dope I like the looks of it great implementation

**Pull request merged**
