### PR TITLE
Enhancement CSS

### PR DESCRIPTION
**Pull request by niko391a**
## List of things changed;
- Added logos to external login services
- Moved navigation bar to the side with corresponding icons
- Centered element for login and register page
- Changed background to use a blurred gradient instead of static color
- Rounded input and main borders

## Main screen
billede

## Login
billede

## Register
billede

## Navigation after logging in
billede

### CODE REVIEW

**Review by Nikolaj787 — APPROVED** [review]
Great changes to the design of our program, to make it look more modern. Also enhances our user experience on the website :D

**Review by Tipskind — APPROVED** [review]
Great implementation of feedback towards the UI. Make sure to keep the branch open for when 'followimplementation' merges. You may want to add further UI adjustment based on your/groups liking.

**Review by DragonFlyersx — APPROVED** [review]
I like the new look especially the gradient and the icons for the nav bar and also it being on the side

**Review by RasmusAChr — CHANGES_REQUESTED** [review]
Very nice visual changes and design decisions - I especially like the new navigation bar and the modern login and registration formular!
There could be some nitpicking about some spacing and button colors, but overall the changes are very welcoming!

However, since the layout for some of the sites has been changed, the End-to-End tests have to be redone to ensure they align with the updated design and functionality.

**Review by RasmusAChr — APPROVED** [review]
I got confused at first because of the many changes, but then i figured out it looks like you have merged another branch into this one and then fixed e2e? At a glance, it looks like its the main branch merged into this.

Nonetheless good to see that the E2E tests are adjusted and are passing this time. It's going to be hell merging the username branch into main after this one xD

**Pull request merged**
