### PR TITLE
Feature send cheeps

### PR DESCRIPTION
**Pull request by DragonFlyersx**
# Sending Cheeps is now Possible

You can now send cheeps by entering them into the form this will store them in the cheeps table.

### Added additions
- Created a form for submitting cheeps
- Added the backend for handling the logic of creating a new CheepDTO object with a nested AuthorDTO object for better being able to send it down the pipeline
- Configured the backend to now Createcheeps as well as create author from the nested AuthorDTO's name
-  Recreated the author table to now have AuthorId stores as an integer instead of text, such that it can autoincrement.
- Updated the migration for the DB
-  Fixed the Time format to only display HH-MM-SS instead of the whole unix timer.
- Added such that if an author does not exist in the table already they will be added when posting their first cheep
- Made it possible to send cheeps from the user timeline and public timeline
- Made sure to redirect to each site after posting, so that we won't experience double requests and errors.

## With these changes Issue number #102 should be solved.

### CODE REVIEW

**Review by Tipskind — APPROVED** [review]
Migration succes, looks good. Author Id functionality looks good.

**Review by Nikolaj787 — APPROVED** [review]
Great changes to the program to fix the bugs we were struggling with

**Comment by DragonFlyersx** [comment]
Test should fail because it is being worked on currently by other team members

**Review by niko391a — APPROVED** [review]

**Review by RasmusAChr — CHANGES_REQUESTED** [review]
Remove unnecessary migrations

**Review by RasmusAChr — APPROVED** [review]
Great to see that the messages are sent securely through the layers.

Nice job using the AuthorDTO to separate concerns. This will help keep the data sent to the client safe by only including what is really needed ;-)

**Pull request merged**
