### PR TITLE
Expanding functionality

### PR DESCRIPTION
**Pull request by DragonFlyersx**
Solved Warning issue
Solved add new fucntionality issue
Solved Constraits for cheep lengths issue
Solved added total page number issues.

There is 3 warning that we deem necessary at the current time

We have set up for expanding the functionality of total page count to be added at a later date.

Re added cheepservice for better onionlayering the project

### CODE REVIEW

**Comment by Tipskind** [comment]
Very nice work

**Review by Nikolaj787 — APPROVED** [review]
Good changes!

**Comment by RasmusAChr** [comment]
Good job removing the warnings :-)

**Review by RasmusAChr — APPROVED** [review]

**Review by Tipskind — APPROVED** [review]
Very nice work. I approve this.

**Pull request merged**
